default: &default
  adapter: postgresql
  encoding: utf8
  template: template0
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: xiaoming_26_development

production:
  <<: *default
  database: xiaoming_26_production
  username: xiaoming_26
  password: <%= ENV['XIAOMING_26_DATABASE_PASSWORD'] %>
