# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6afe1525b761a3c55c27401d850115f42afb17be83b1318573e8de951cbb0e540694c5a8f622af33f0c904504f26f7a6bf1c601b4b07b54465121cc5adf29d

test:
  secret_key_base: d8f96a83bc417a9338e4212a3586a7a6dafecb66c53c3e4e17f16205b1efc408a7f5484ff88c82cca3d01da1f983bd27e70721e1286a806ffbd88a13357bbb2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
